kind: "Template"
apiVersion: "v1"
metadata:
  name: "dummy" 
parameters:
- description: "The version of the application"
  name: "VERSION"
  value: "latest"
  required: true
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "dummy" 
  spec:
    source: 
      type: "Binary"
    strategy: 
      type: "Docker"
      dockerStrategy:
         dockerfilePath: Dockerfile
    output: 
      to:
        kind: "ImageStreamTag"
        name: "dummy:${VERSION}"
- kind: "ImageStream"
  apiVersion: "v1"
  metadata:
    name: "dummy" 
      
