FROM centos:7


USER jenkins

ENV JAVA8=1.8.0 \ 
    JENKINS_VERSION=3.29
    DOCKER_COMPOSE=1.23.2 \
    OC3_4=3.4.1.44um/re
    
ENV PATH=/usr/lib/ant/apache-ant-1.9.10/bin:/opt/rh/rh-git29/rot/bin\
    ARTIFACTORY_URL=https://artifacgtory:8080/artifactory
    
 
#Installing Yum packages
RUN rm -f /etc/y
